I made a task for the Java classes section and added a condition before the entry point
AleksandrVoyteshenko/JavaTask pull request #1
Opened 2020-10-28 07:30 UTC by AleksandrVoyteshenko

…re the entry point

2020-11-09 11:13 UTC, nitrogen16 reviewed
исправить комментарии

2020-11-09 11:13 UTC, nitrogen16 commented on src/javaclasses/TheDatabaseOfTheInstitution.java
> +        Scanner g = new Scanner(System.in);
разнести логические блоки по отдельным методам

2020-11-09 11:13 UTC, nitrogen16 commented on src/javaclasses/TheDatabaseOfTheInstitution.java
> +        Scanner y = new Scanner(System.in);
каждый раз содавать объект Scanner? а зачем, если можно использовать один

2020-11-25 05:10 UTC, nitrogen16 requested changes
Fix the comments.

2020-11-25 05:10 UTC, nitrogen16 commented on src/java_classes/TheDatabaseOfTheInstitution.java
> +
extra space

2020-11-25 05:10 UTC, nitrogen16 commented on src/java_classes/Student.java
> +    private String id;
id should be int

2020-11-25 05:10 UTC, nitrogen16 commented on src/java_classes/TheDatabaseOfTheInstitution.java
> +
extra space

2020-11-25 05:10 UTC, nitrogen16 commented on src/java_classes/TheDatabaseOfTheInstitution.java
> +            if (parseYear(st.getDateOfBirth().substring(6)) > parseYear(year)) {
substring is not a good approach
it works with 20-05-2020
but if we have 1-1-2020?
use DateFormatter
The idea is to work with Date, not with a String. Therefore, parse String to Date, then get a year from this Date

2020-11-28 08:49 UTC, nitrogen16 requested changes
Fix the comment. Then I'll approve

2020-11-28 08:49 UTC, nitrogen16 commented on src/java_classes/TheDatabaseOfTheInstitution.java
> +        Scanner input = new Scanner(System.in);
Each time you call method a new instance of Scanner is created.
Why? Make ONE instance of Scanner for all method calls.

2020-11-28 11:06 UTC, AleksandrVoyteshenko commented on src/java_classes/TheDatabaseOfTheInstitution.java
> +        Scanner input = new Scanner(System.in);
fixed the project structure, left one copy of the scanner for all methods

2020-11-30 19:02 UTC, nitrogen16 approved these changes
More or less it's okay

2020-12-01 06:26 UTC, closed without merging