Tasks in the java fundamentals section
AleksandrVoyteshenko/JavaTask pull request #2
Opened 2020-10-28 07:50 UTC by AleksandrVoyteshenko

2020-11-09 11:07 UTC, nitrogen16 reviewed
класс с заданием закомменчен, почему?

2020-11-09 11:07 UTC, nitrogen16 commented on src/javafundamentals/MainTask.java
> +    /* MainTask.1 Приветствовать любого пользователя при вводе его имени через командную строку
почему всё закомменчено?

2020-11-25 05:18 UTC, nitrogen16 requested changes
Fix the comments.

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        MainTask.helloUser();
Should look look like this:
helloUser();
reverseElements();
outPutElement(); and etc.

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        Scanner sc = new Scanner(System.in);
In total 3 objects of Scanner.
Use one object.

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        String[] month = {"January", "February", "March", "April", "May", "June",
You have an array.
Create a ENUM or a separate common array.
What if you want to use it for other methods in the future? This array is specific for this method only. 
Method should perform only its action. It should not contain any other data.Bad practice.

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        int[] a = {1, 2, 3, 4, 5};
why 5 elements? What if I want 100, 244, 1000?

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        String str = "5501584";
I want to enter "sadasdas", "2131231231", "12312ewaewqe24312312". Will it work?

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/MainTask.java
> +        System.out.println("Введите целые числа: ");
тогда уже введите через пробел
я могу ввести число и нажать enter

2020-11-25 05:18 UTC, nitrogen16 commented on src/java_fundamentals/OptionalTask.java
> +        System.out.println("Введите числа" );
через пробел ввести или как?

2020-11-28 12:50 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        String str = "5501584";
Yes. Introduced the scanner

2020-11-28 12:51 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        System.out.println("Введите целые числа: ");
Fixed comments

2020-11-28 13:39 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        int[] a = {1, 2, 3, 4, 5};
Fixed comment. Generate a given number of random numbers

2020-11-28 13:40 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        String[] month = {"January", "February", "March", "April", "May", "June",
вынес информацию за пределы методов и сделал доступной всем методам

2020-11-28 13:40 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/OptionalTask.java
> +        System.out.println("Введите числа" );
исправил

2020-11-28 13:47 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        MainTask.helloUser();
fixed

2020-11-28 13:47 UTC, AleksandrVoyteshenko commented on src/java_fundamentals/MainTask.java
> +        Scanner sc = new Scanner(System.in);
вынес сканнер за методы

2020-11-30 19:13 UTC, nitrogen16 requested changes
Please see comments

2020-11-30 19:13 UTC, nitrogen16 commented on src/main/java/java_fundamentals/MainTask.java
> +        String element = scanner.nextLine();
![2020-11-30_22h04_39](https://user-images.githubusercontent.com/21346318/100652669-4e603a80-3358-11eb-8926-251bc5c81420.png)

2020-11-30 19:13 UTC, nitrogen16 commented on src/main/java/java_fundamentals/MainTask.java
> +        String number = scanner.nextLine();
![2020-11-30_22h08_16](https://user-images.githubusercontent.com/21346318/100652941-b9117600-3358-11eb-8160-fa18f401c035.png)

2020-11-30 19:13 UTC, nitrogen16 commented on src/main/java/java_fundamentals/OptionalTask.java
> +    public static void main(String[] args) {
![2020-11-30_22h11_18](https://user-images.githubusercontent.com/21346318/100653288-389f4500-3359-11eb-8368-548465b7a5f1.png)

2020-12-04 09:23 UTC, nitrogen16 approved these changes

2020-12-04 09:41 UTC, merged