I made a task for the collection without the taxi company hierarchy
AleksandrVoyteshenko/JavaTask pull request #3
Opened 2020-10-28 08:10 UTC by AleksandrVoyteshenko

2020-11-09 11:10 UTC, nitrogen16 reviewed
убрать лишние классы из ПРа

2020-11-09 11:10 UTC, nitrogen16 commented on src/javacollections/stringmanipulation/Poem.java
> +public class Poem {
к чему это?

2020-11-09 11:10 UTC, nitrogen16 commented on src/javacollections/stringmanipulation/LinesFromTheFile.java
> +public class LinesFromTheFile {
к чему это?

2020-11-25 05:26 UTC, nitrogen16 requested changes
Fix the comments

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/maintask/ratecar/RateCar.java
> +
extra space

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/optionaltask/Poem.java
> +                poem.toString().replace("[","").replace("]", "").replace(", ", ""));
why?

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/optionaltask/Poem.java
> +                poem.toString().replace("[","").replace("]", "").replace(", ", ""));
why?

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        int poolPrice = 0;
create a separate method

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        Collections.sort(taxipool, Comparator.comparingDouble(Car::getConsumption));
create a separate method

2020-11-25 05:26 UTC, nitrogen16 commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        System.out.println("\nВведите минимальную скорость: ");
create a separate method

2020-11-28 13:56 UTC, AleksandrVoyteshenko commented on src/javacollections/stringmanipulation/Poem.java
> +public class Poem {
задание OptionalTask

2020-11-28 13:57 UTC, AleksandrVoyteshenko commented on src/javacollections/stringmanipulation/LinesFromTheFile.java
> +public class LinesFromTheFile {
Задание OptionalTask

2020-11-28 13:59 UTC, AleksandrVoyteshenko commented on src/java_collections/optionaltask/Poem.java
> +                poem.toString().replace("[","").replace("]", "").replace(", ", ""));
Убрал. Делал для наглядного сравнения в консоли

2020-11-28 14:03 UTC, AleksandrVoyteshenko commented on src/java_collections/optionaltask/Poem.java
> +                poem.toString().replace("[","").replace("]", "").replace(", ", ""));
Выводит стих в отсортированном порядке

2020-11-28 14:10 UTC, AleksandrVoyteshenko commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        int poolPrice = 0;
fixed

2020-11-28 14:10 UTC, AleksandrVoyteshenko commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        Collections.sort(taxipool, Comparator.comparingDouble(Car::getConsumption));
fixed

2020-11-28 14:10 UTC, AleksandrVoyteshenko commented on src/java_collections/maintask/TaxiCompanyManagement.java
> +        System.out.println("\nВведите минимальную скорость: ");
fixed and took out one scanner

2020-11-28 14:21 UTC, AleksandrVoyteshenko commented on src/java_collections/maintask/ratecar/RateCar.java
> +
fixed

2020-11-30 19:25 UTC, nitrogen16 requested changes
Please see comments

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/optionaltask/Poem.java
> +        poem.sort(((o1, o2) -> o1.length() - o2.length()));
poem.sort((Comparator.comparingInt(String::length)));

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/optionaltask/Poem.java
> +    public static void main(String[] args) throws IOException {
IOException? Are you sure?

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/optionaltask/LinesFromTheFile.java
> +        file.sort(((o1, o2) -> o1.length() - o2.length()));
file.sort((Comparator.comparingInt(String::length)));

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/maintask/ratecar/RateCar.java
> +    COMFORT_CAR , ECONOMY_CAR, BUSINESS_CAR;
BUSINESS_CAR is not used.
Use or delete. My suggestion is to use this

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/maintask/TaxiCompanyManagement.java
> +        System.out.println("\nВведите минимальную скорость: ");
![2020-11-30_22h20_56](https://user-images.githubusercontent.com/21346318/100654343-b021a400-335a-11eb-9661-228f864a7bfa.png)

2020-11-30 19:25 UTC, nitrogen16 commented on src/main/java/java_collections/maintask/TaxiCompanyManagement.java
> +        List<Car> taxipool = Arrays.asList(
taxipool -> taxiPool
camel style

2020-12-09 13:33 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/optionaltask/Poem.java
> +        poem.sort(((o1, o2) -> o1.length() - o2.length()));
OK

2020-12-09 13:35 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/optionaltask/Poem.java
> +    public static void main(String[] args) throws IOException {
Fixed

2020-12-09 13:35 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/optionaltask/LinesFromTheFile.java
> +        file.sort(((o1, o2) -> o1.length() - o2.length()));
fixed

2020-12-09 13:38 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/maintask/ratecar/RateCar.java
> +    COMFORT_CAR , ECONOMY_CAR, BUSINESS_CAR;
Yes, I used this rate.

2020-12-09 13:45 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/maintask/TaxiCompanyManagement.java
> +        System.out.println("\nВведите минимальную скорость: ");
fixed

2020-12-09 13:49 UTC, AleksandrVoyteshenko commented on src/main/java/java_collections/maintask/TaxiCompanyManagement.java
> +        List<Car> taxipool = Arrays.asList(
fixed

2020-12-10 12:33 UTC, nitrogen16 requested changes

2020-12-10 12:33 UTC, nitrogen16 commented on src/main/java/java_collections/maintask/TaxiCompanyManagement.java
> + * 10. Таксопарк. Определить иерархию легковых автомобилей. Создать таксопарк. Подсчитать стоимость автопарка. Провести сортировку автомобилей парка по расходу топлива. Найти автомобиль в компании, с
Провести сортировку автомобилей парка по расходу топлива. Найти автомобиль в компании, соответствующий заданному диапазону параметров скорости.
Was not implemented.

2020-12-11 08:57 UTC, nitrogen16 approved these changes

2020-12-11 09:09 UTC, merged