created methods that implement exceptions
AleksandrVoyteshenko/JavaTask pull request #4
Opened 2020-11-11 10:15 UTC by AleksandrVoyteshenko

2020-11-16 13:58 UTC, nitrogen16 reviewed
Needs Rework.

2020-11-16 13:58 UTC, nitrogen16 commented on bash.exe.stackdump
> +Stack trace:
что за файл и к чему он в этом ПР?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет факультета");
какого нет факультета?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет группы");
какой нет группы?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете студентов");
каких студентов?
"В университете студентов" это как понять?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/group/ElectricGroup.java
> +
это пустые строки к чему?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/group/RoadConstructionGroup.java
> +        return "RoadConstructionGroup{} " + super.toString();
странная строка
она зачем?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +
куча переносов, для чего и зачем?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                " находится вне допустимого значения");
а какого допустимого значения? какое значение является допустимым?

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("У стеднта " + student.getSurname() + " " + student.getFirstname() +
студента

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                if (student.getEvaluationOfTheGeneralItem() < 0 || student.getEvaluationOfTheGeneralItem() > 10 ||
if очень громоздкий
следует попробовать объединить предметы в один список
либо отдельный метод boolean для if сделать

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +            for (StudentInformation student : students) {
этот for напрашивается быть вынесенным в отдельный метод

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +        for (StudentInformation student : students) {
этот тоже

2020-11-16 13:58 UTC, nitrogen16 commented on src/javaerrorandexception/UniversityAdministration.java
> +                    x++;
неудобоваримая логика, надо постараться упростить вычисления

2020-11-25 05:32 UTC, nitrogen16 requested changes
Fix the comments

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new NullPointerException("На факультете нет групп");
каком факультете и каких групп?

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет студентов");
каких студентов?

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new NullPointerException("У студента " + student.getSurname() + " " + student.getFirstname() +
а каких предметов нету у студента?

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new IllegalArgumentException("Оценка студента " + student.getSurname() + " " + student.getFirstname() +
а какая оценка? какой диапазон?

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/group/ElectricGroup.java
> +
extra space

2020-11-25 05:32 UTC, nitrogen16 commented on src/java_error_and_exception/UniversityAdministration.java
> +    Scanner sc = new Scanner(System.in);
Scanner uses in two places. Use one Scanner.
Pattern Singleton as an option.

2020-11-28 16:14 UTC, AleksandrVoyteshenko commented on bash.exe.stackdump
> +Stack trace:
deleted

2020-11-28 16:14 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет факультета");
corrected

2020-11-28 16:14 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет группы");
corected

2020-11-28 16:15 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете студентов");
вообще в универе отсутствуют студенты

2020-11-28 16:15 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/group/ElectricGroup.java
> +
deleted

2020-11-28 16:15 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                    throw new NullPointerException("У стеднта " + student.getSurname() + " " + student.getFirstname() +
corrected

2020-11-28 16:16 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                if (student.getEvaluationOfTheGeneralItem() < 0 || student.getEvaluationOfTheGeneralItem() > 10 ||
сделал отдельный метод который возвращает значение проверки оценки по диапазону, true или false

2020-11-28 17:47 UTC, AleksandrVoyteshenko commented on src/javaerrorandexception/UniversityAdministration.java
> +                    x++;
разделил ифы на два условия

2020-11-28 17:48 UTC, AleksandrVoyteshenko commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new NullPointerException("На факультете нет групп");
исправил

2020-11-28 17:48 UTC, AleksandrVoyteshenko commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new NullPointerException("В университете нет студентов");
сделал проверку листа на пустоту.

2020-11-28 17:49 UTC, AleksandrVoyteshenko commented on src/java_error_and_exception/UniversityAdministration.java
> +                    throw new IllegalArgumentException("Оценка студента " + student.getSurname() + " " + student.getFirstname() +
изменил метод

2020-11-28 17:49 UTC, AleksandrVoyteshenko commented on src/java_error_and_exception/group/ElectricGroup.java
> +
убрал

2020-11-28 17:49 UTC, AleksandrVoyteshenko commented on src/java_error_and_exception/UniversityAdministration.java
> +    Scanner sc = new Scanner(System.in);
вынес

2020-11-30 19:39 UTC, nitrogen16 requested changes
Cooments. Fix. Was not tested

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +        );
![2020-11-30_22h28_05](https://user-images.githubusercontent.com/21346318/100654789-65ecf280-335b-11eb-9cfd-e39d234f51e6.png)

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +                new StudentInformation("Боженок", "Андрей", "1-20", "Building", "Mathematics", 10, "EngineeringGraphics", 4),
BuildingFaculty and PowerFaculty are not used. Why?

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +        UniversityAdministration.availabilityOfFaculty(students);
What it is doing? This method

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +        UniversityAdministration.availabilityOfGroup(students);
What it is doing? This method

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +        UniversityAdministration.availabilityOfItem(students);
![2020-11-30_22h35_25](https://user-images.githubusercontent.com/21346318/100655531-79e52400-335c-11eb-86a5-a6cc7c44f09c.png)

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/UniversityAdministration.java
> +        System.out.println("Средний балл на факультете " + facultyName + " в группе " + groupName + " по предмету " + itemName + " = " + sum / x);
![2020-11-30_22h37_08](https://user-images.githubusercontent.com/21346318/100655670-abf68600-335c-11eb-829c-4673e218f50a.png)
Where is the exception?

2020-11-30 19:39 UTC, nitrogen16 commented on src/main/java/java_error_and_exception/UniversityAdministration.java
> +        System.out.println("Средний балл по предмету " + nameItem + " для всего унивеситета = " + ball / y);
Exception?????

2020-12-01 15:10 UTC, AleksandrVoyteshenko commented on src/main/java/java_error_and_exception/StudentOfUniversity.java
> +        UniversityAdministration.availabilityOfItem(students);
Becouse this is different metods. They output the result based on a set of conditions.

2020-12-14 06:04 UTC, AleksandrVoyteshenko commented on src/main/java/java_error_and_exception/UniversityAdministration.java
> +        System.out.println("Средний балл по предмету " + nameItem + " для всего унивеситета = " + ball / y);
fixed

2021-02-02 18:31 UTC, merged