Input/output
AleksandrVoyteshenko/JavaTask pull request #7
Opened 2020-11-19 11:44 UTC by AleksandrVoyteshenko

Made the MainTask and 3 OptionalTask items of the Java input /output section

2020-11-25 05:47 UTC, nitrogen16 requested changes
src/input_and_output/optionaltask/first_task/random numbers.txt
этот файл генерится как я понимаю
зачем его кидать в ПР?

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/maintask/WorkWithFiles.java
> +    public static void writingStructureToFile(File album) throws IOException {
Did you try it on any folder?

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/optionaltask/first_task/RandomNumbers.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter("src/input_and_output/optionaltask/first_task/random numbers.txt"));
Har coded value. Create a file with path variable

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/optionaltask/first_task/RandomNumbers.java
> +            BufferedReader reader = new BufferedReader(new FileReader("src/input_and_output/optionaltask/first_task/random numbers.txt"));
Again hard coded path. Avoid this. What if you have 50 methods? 50 times you should repeat it.

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedReader reader = new BufferedReader(new FileReader("src/input_and_output/optionaltask/tenth_task/text.txt"));
Again hard coded value. Avoid this.

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("src/input_and_output/optionaltask/tenth_task/text.txt"));
and again

2020-11-25 05:47 UTC, nitrogen16 commented on src/input_and_output/optionaltask/twelfth_task/WorkWithFileAndText.java
> +                    BufferedWriter writerWord = new BufferedWriter(new FileWriter("src/input_and_output/optionaltask/twelfth_task/word.txt"));
2 instances of BufferedWriter writerWord. Why?

2020-11-25 07:33 UTC, AleksandrVoyteshenko commented on src/input_and_output/maintask/WorkWithFiles.java
> +    public static void writingStructureToFile(File album) throws IOException {
Yes, I did. The method reads the structure of folders and files in the specified directory File album, namely the parent directory of Amon Amarth and writes the structure to the file task.txt

2020-11-25 07:44 UTC, AleksandrVoyteshenko commented on src/input_and_output/optionaltask/first_task/RandomNumbers.java
> +            BufferedReader reader = new BufferedReader(new FileReader("src/input_and_output/optionaltask/first_task/random numbers.txt"));
it is necessary to create a file in the directory where the job is located. but it is possible to create a separate file folder for all jobs: src/job_files/

2020-11-28 08:54 UTC, nitrogen16 requested changes
Hard coded paths values

2020-11-28 08:54 UTC, nitrogen16 commented on src/input_and_output/optionaltask/first_task/RandomNumbers.java
> +            BufferedReader reader = new BufferedReader(new FileReader("src/input_and_output/optionaltask/first_task/random numbers.txt"));
FileReader() retrives a path as a parameter. Therefore, path you use should be as a varible. Better to create a property file.

2020-11-30 19:50 UTC, nitrogen16 requested changes
Fix the comments

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/optionaltask/first_task/RandomNumbers.java
> +    }
[random numbers.txt](https://github.com/AleksandrVoyteshenko/JavaTask/files/5618338/random.numbers.txt)
this is the result....

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            String line = null;
null is redundant

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            String word = null;
null is redundant

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("src/main/resources/proza.txt"));
"src/main/resources/proza.txt" is used 4 times!!!!!
why?

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/optionaltask/twelfth_task/WorkWithFileAndText.java
> +                    writerWord.write("Введенное слово " + str.toUpperCase() + " в тексте не найдено");
Should we write this word into file if it was not found?

2020-11-30 19:50 UTC, nitrogen16 commented on src/main/java/input_and_output/maintask/WorkWithFiles.java
> + * Реализовать программу которая будет получать в качестве аргумента командной строки путь к директории, например "D:/movies".
Реализовать программу которая будет получать в качестве аргумента командной строки путь к директории, например "D:/movies".
Где это реализовано?

2020-12-01 15:14 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/optionaltask/first_task/RandomNumbers.java
> +    }
Yes. What is wrong as a result?

2020-12-01 15:15 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/optionaltask/twelfth_task/WorkWithFileAndText.java
> +                    writerWord.write("Введенное слово " + str.toUpperCase() + " в тексте не найдено");
I realized that there is no given condition in the task, I replayed it!

2020-12-09 12:49 UTC, AleksandrVoyteshenko commented on src/input_and_output/optionaltask/twelfth_task/WorkWithFileAndText.java
> +                    BufferedWriter writerWord = new BufferedWriter(new FileWriter("src/input_and_output/optionaltask/twelfth_task/word.txt"));
fixed

2020-12-09 12:54 UTC, AleksandrVoyteshenko commented on src/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("src/input_and_output/optionaltask/tenth_task/text.txt"));
fixed

2020-12-09 12:54 UTC, AleksandrVoyteshenko commented on src/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedReader reader = new BufferedReader(new FileReader("src/input_and_output/optionaltask/tenth_task/text.txt"));
fixed

2020-12-10 12:28 UTC, nitrogen16 requested changes
Different folders in path was not implemented.

2020-12-10 12:28 UTC, nitrogen16 commented on src/main/java/input_and_output/maintask/WorkWithFiles.java
> + * Реализовать программу которая будет получать в качестве аргумента командной строки путь к директории, например "D:/movies".
Was not done!

2020-12-12 15:51 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/maintask/WorkWithFiles.java
> + * Реализовать программу которая будет получать в качестве аргумента командной строки путь к директории, например "D:/movies".
fixed

2020-12-16 08:21 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            String line = null;
fixed

2020-12-16 08:21 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            String word = null;
fixed

2020-12-16 08:22 UTC, AleksandrVoyteshenko commented on src/main/java/input_and_output/optionaltask/tenth_task/ReadFile.java
> +            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("src/main/resources/proza.txt"));
fixed

2020-12-23 15:11 UTC, merged