Did the job with threads
AleksandrVoyteshenko/JavaTask pull request #8
Opened 2020-11-24 11:58 UTC by AleksandrVoyteshenko

Through the loop, I created a thread for each entity (auto). Used the class Thread and the interface Runnable. Used the capabilities of the java.util.concurrent.* package, namely the Semaphore synchronizer, according to the assignment. Using the tryAcquire (long timeout, TimeUnit unit) method of the Semaphore class, I specified the waiting time for permission to access the resource (parking) with an unlimited number of requests.

2020-11-25 05:52 UTC, nitrogen16 requested changes
Fix the comments

2020-11-25 05:52 UTC, nitrogen16 commented on src/java_threads/Parking.java
> +    public static class Car implements Runnable {
Why it's not in a separate class?

2020-11-25 05:52 UTC, nitrogen16 commented on src/java_threads/Parking.java
> +                Thread.sleep(9000);
почему 9 секунд?

2020-11-25 06:06 UTC, AleksandrVoyteshenko commented on src/java_threads/Parking.java
> +                Thread.sleep(9000);
Это время сна потока, когда машина находится на парковке, а владелец ушел по делам так сказать. Возможно поставить любое время, любое количество машин-потоков (numberCar <= 10 в цикле фор) и парковочных мест (длину массива).

2020-11-25 06:22 UTC, AleksandrVoyteshenko commented on src/java_threads/Parking.java
> +    public static class Car implements Runnable {
I created a separate class for cars

2020-11-25 11:42 UTC, ZeddzZ commented on src/java_threads/Car.java
> +    private static final Semaphore turn = new Semaphore(5, true);
Что за магические числа? Что означает 5? Если это количество мест на парковке, то почему оно не передается параметром. И какое вообще отношение парковочное место имеет к классу машина? Не должен ли это быть отдельный класс?

2020-11-25 11:42 UTC, ZeddzZ commented on src/java_threads/Car.java
> +            if (turn.tryAcquire(2, TimeUnit.SECONDS) == false) {
Что за магическое число 2? Лучше вынести его в переменную, чтобы было понятно, что передается в метод.

2020-11-25 11:42 UTC, ZeddzZ commented on src/java_threads/Parking.java
> +        for (int numberCar = 1; numberCar <= 10; numberCar++) {
Что за магическое число 10? Если это количество машин, лучше вынести его в отдельную переменную.
Ещё лучше - запрашивать число машин и парковочных мест у пользователя, а так же минимальное и максимальное время, которое машина может стоять на парковке.

2020-11-25 11:42 UTC, ZeddzZ commented on src/java_threads/Parking.java
> +            new Thread(new Car(numberCar)).start();
Почему машина является потоком?
С точки зрения логики, потоком должно быть парковочное место, а объектом, который занимает его и не даёт доступ другим - машина.

2020-11-25 11:42 UTC, ZeddzZ commented on src/java_threads/Parking.java
> +            Thread.sleep(1000);
Что за магическое число 1000? Почему именно тысяча? Лучше вынести в отдельную переменную.

2020-12-10 10:12 UTC, nitrogen16 reviewed
Fix comments.

2020-12-10 10:12 UTC, nitrogen16 commented on src/main/java/java_threads/Parking.java
> +    static int downtime;
Pass variables used in car as method parameters.

2020-12-10 13:41 UTC, AleksandrVoyteshenko commented on src/main/java/java_threads/Parking.java
> +            Thread.sleep(interval * 1000);
fixed

2020-12-10 13:41 UTC, AleksandrVoyteshenko commented on src/main/java/java_threads/Car.java
> +                Thread.sleep(Parking.downtime * 1000);
fixed

2020-12-11 08:56 UTC, nitrogen16 approved these changes

2020-12-11 09:08 UTC, merged